version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: grive-cache-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: ["redis-server", "--appendonly yes", "--maxmemory-policy", "allkeys-lru"]
    environment:
      - REDIS_MAXMEMORY=256mb
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: "30s"
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
